function example()
%EXAMPLE  usage of metric optimzed gating functions
%
% * read philips raw data (.data/.list), 
% * perform metric optimized gating, and
% * analyze flow
% 


%% Configure 

% Path to MOG toolbox
mogToolboxPath = fileparts( which( mfilename ) );


%% Add Dependencies

origPaths = path;

addpath( genpath( mogToolboxPath ) );

resetPath = onCleanup( @() path( origPaths ) );


%% Metric Optimized Gating

MOG_Tool,


%% Analyse Flow

analyze_pcmr,

    % Alternatively, 
    %
    % patchedMatFilePath = '';   % name of _patched.mat file generated by MOG_Tool
    % dx                 = NaN;  % voxel dimension, in mm, read from protocol .txt file if unspecified
    % dy                 = NaN;  % voxel dimension, in mm, read from protocol .txt file if unspecified
    % nFrames            = NaN;  % number of time frames to reconttruct, true number of time frames used if unspecified
    % doRectify          = true; % rectify velocity/flow if negative
    % doAlignSystole     = true; % shift time frames so systolic peack occurs at 30% of cardiac cycle
    % 
    % analyze_pcmr( patchedMatFilePath, dx, dy, nFrames, doRectify, doAlignSystole )


end 
